[package]
name = "todoin-application"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
# layer deps
todoin-domain = { version = "0.1.0", path = "../domain" }
serde.workspace = true
serde_json.workspace = true

# shared deps
sqlx.workspace = true
thiserror.workspace = true
